id: P004412
initial_creation_type: ocr
source_metadata:
  id: bdr:W7545
  title: བརྡ་གསར་རྙིང་གི་ཁྱད་པར་བསྟན་པ་གསར་བུའི་བློ་གྲོས་སྐྱེད་བྱེད།
  author: ''
  volumes:
    6a1d7e4021a8481c9b3566d43f1c35f0:
      image_group_id: I1CZ990
      title: ''
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
